/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.shoe

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'org.shoe.greeting' plugin.
 */
class Gradle_plugin_1PluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("org.shoe.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
